#!/bin/bash
sage headfinal-nst.py 3 19 161 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 162 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 163 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 164 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 165 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 160 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 166 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 167 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 168 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 169 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 171 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 172 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 173 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 174 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 175 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 170 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 176 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 177 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 178 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 179 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 191 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 192 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 193 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 194 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 195 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 190 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 196 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 197 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 198 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 199 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 191 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 192 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 193 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 194 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 195 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 190 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 196 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 197 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 198 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 199 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 281 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 282 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 283 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 284 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 285 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 280 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 286 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 287 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 288 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 289 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 211 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 212 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 213 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 214 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 215 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 219 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 216 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 217 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 219 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 219 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 221 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 222 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 223 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 224 "/home/yan/crypfinal/batchnst/"&
sage headfinal-nst.py 3 19 225 "/home/yan/crypfinal/batchnst/"&


