#!/bin/bash
sage solution.py 0&
sage solution.py 1&
sage solution.py 2&
sage solution.py 3&
sage solution.py 4&
sage solution.py 5&
sage solution.py 6&
sage solution.py 7&
sage solution.py 8&
sage solution.py 9&
sage solution.py 10&
sage solution.py 11&
sage solution.py 12&
sage solution.py 13&
sage solution.py 14&
sage solution.py 15&
sage solution.py 16&
sage solution.py 17&
sage solution.py 18&
sage solution.py 19&
sage solution.py 20&
sage solution.py 21&
sage solution.py 22&
sage solution.py 23&
sage solution.py 24&
sage solution.py 25&
sage solution.py 26&
sage solution.py 27&
sage solution.py 28&
sage solution.py 29&
sage solution.py 30&
sage solution.py 31&
